apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment-nopdb
  labels:
    entorno: produccion # Esto dispara la política
  # Falta la anotación: iso27001/pdb-configured: true
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app
        image: nginx
